### ISSUE TITLE
Renovacion diagrama de Gantt

### ISSUE THREAD

**Issue by Matias-Harper** [marianaiv/seismic-alerts#17]

**Comment by Matias-Harper** [comment]
subo dos diagramas uno en excel y una imagen de la distribución
 
[Diagrama Gantt MLGI.xlsx](https://github.com/marianaiv/seismic-alerts/files/10087519/Diagrama.Gantt.MLGI.xlsx)
![Diagrama de Gantt](https://user-images.githubusercontent.com/106800619/203869455-5bb0be2b-63f6-4052-8cfa-bf48275377f3.jpg)

**Comment by marianaiv** [comment]
El diagrama se encuentra en documentos
