### ISSUE TITLE
Tecnologías a utilizar

### ISSUE THREAD

**Issue by marianaiv** [marianaiv/seismic-alerts#3]
Tenemos que escoger las herramientas que vamos a usar en el proyecto

**Comment by IDell49** [comment]
# Stack tecnologico

Github: Repositorio MAIN del proyecto, con branches para cada participante, se usan Issues para distribuir las tareas en un nivel atomico

Python: Se va a usar pandas para la mayoria del procesamiento

APIs: se van a extraer datos desde APIs, solo parte de la informacion fue otorgada al comienzo del proyecto

Base de datos SQL: se usa una base de datos SQL(relacional) ya que nuestras tablas van a ser estructuradas, con la posiblidad de hacer queries extrayendo la informacion necesaria, con una estructura de copo de nieve (una tabla de hechos, con sus dimensiones en varios niveles)

Servicios en la nube: Vamos a utilizar datasets con estimados de mas de 4 millones de filas, guardar el data-lake en un servicio en la nube tiene sentido, alli se usaran los servicios de AWS para guardar, transformar y cargar datos a una base de datos SQL integrada en la plataforma.

Al momento de elegir entre AWS/Azure/GoogleCloud (top 3 popularidad) AWS se lleva el cupo por:

> popularidad: AWS primero, Azure segundo con 22%, y GoogleCloud tercero. El resto de los servicios de nube estuvieron subiendo en popularidad estos ultimos 3 años

> billing: tiene un dashboard integrado para saber el costo por minuto si es que hay alguno


> longevidad: Amazon y Microsoft tienen politicas de seguridad para sus usuarios, pero Google es conocido por dejar de soportar productos que les dejan de interesar. 

> latencia: Amazon posee la mayor cantidad de nodos regionales, garantizando la menor cantidad de latencia posible a cualquier usuario.

> estabilidad: AWS posee un maximo de 3hrs seguidas offline en toda su historia
, Azure, en cambio, posee un maximo de 40 horas offline. Por ultimo google solo 14 minutos, pero esto es entendible ya que su escala es mucho menor 

> tecnologias: AWS tiene ventaja en variedad de servicios de MachineLearning, que nos va a permitir implementar modelos facilmente para la clasificar los terremotos.  

> regiones: lider en cantidad de regiones y zonas habilitadas

**Comment by IDell49** [comment]
Definido en:
![image](https://user-images.githubusercontent.com/107069515/202484204-497ef686-0deb-4c42-9949-dc0b732187c3.png)
