### ISSUE TITLE
Lectura de archivos de Japón

### ISSUE THREAD

**Issue by marianaiv** [marianaiv/seismic-alerts#5]
Lectura y glosario de datos de sismos en japón

Tareas:
- [x] Leer los archivos a partir de 2018
- [x] Hacer un diccionario de las columna

**Comment by IDell49** [comment]
Se consiguio el url desde "http://service.iris.edu/fdsnws/event/docs/1/builder/", donde se especifico la region y la franja horaria
(2018-01-01).

Los separadores se pueden ver descargando el .csv, con un editor de texto

Las primeras 4 filas son metadata, entonces se omiten
```python
url = "http://service.iris.edu/fdsnws/event/1/query?starttime=2018-01-01T00:00:00&orderby=time&format=geocsv&maxlat=45.847&minlon=125.272&maxlon=148.914&minlat=24.070&nodata=404"
df = pd.read_csv(url, sep='|',skiprows=4)
df = df[df.EventLocationName.str.contains('JAPAN')]
```


# Diccionario de atributos:

- EventID: id del evento

- Time: momento del event

- Latitude.

- Longitude.

- Depth: que tan profundo es el sismo, impacta a su peligrosidad

- Author: autor de la recopilacion de los datos en esta api

- Catalog: catalogo de donde se obtuve este dataframe

- Contributor: - 

- ContributorID: - 

- MagType: categorizacion del sismo segun su magnitud

- Magnitude.

- MagAuthor: - 

- EventLocationName: Localidad en la que se ocasiono el sismo

**Comment by IDell49** [comment]
Los datos parecen ser insuficientes, tambien en la propia pagina de la API te redirigen hacia https://earthquake.usgs.gov/fdsnws/event/1/ como base de datos oficial para estudios sismologicos.
