### ISSUE TITLE
Densidad poblacional en México

### ISSUE THREAD

**Issue by Matias-Harper** [marianaiv/seismic-alerts#9]

**Comment by Matias-Harper** [comment]
El 77% de la población vive en zonas urbanas.
Las ciudades que concentran mayor población son (censo 2010):
Ciudad de México: 192.318.29
Guadalajara: 4.095.853
Monterey: 3.664.331
Puebla: 2.109.049

**Comment by leo1489** [comment]
[riesgo sismico mexico local-estad.xlsx](https://github.com/marianaiv/seismic-alerts/files/10025327/riesgo.sismico.mexico.local-estad.xlsx)

**Comment by leo1489** [comment]
[DENSIDAD-MUNS-MEXICO.xlsx](https://github.com/marianaiv/seismic-alerts/files/10025894/DENSIDAD-MUNS-MEXICO.xlsx)

**Comment by leo1489** [comment]
> [riesgo sismico mexico local-estad.xlsx](https://github.com/marianaiv/seismic-alerts/files/10025327/riesgo.sismico.mexico.local-estad.xlsx)


Fuente 
CEDRUS (2019), con base en INEGI. Censo General de Población y Vivienda 2010, Encuesta Intercensal 2015 y Marco Geoestadístico Nacional 2017.

**Comment by leo1489** [comment]
[Densidad_Población_mx.xlsx](https://github.com/marianaiv/seismic-alerts/files/10061640/Densidad_Poblacion_mx.xlsx)
fuente:
https://cuentame.inegi.org.mx/poblacion/densidad.aspx?tema=P

**Comment by leo1489** [comment]
[mx-cities-lat-lon-pop.csv](https://github.com/marianaiv/seismic-alerts/files/10077001/mx-cities-lat-lon-pop.csv)
[estructura_00.xlsx](https://github.com/marianaiv/seismic-alerts/files/10077002/estructura_00.xlsx)

**Comment by leo1489** [comment]
script densidad_pop_mx por estados
[density_mx_states.zip](https://github.com/marianaiv/seismic-alerts/files/10087653/density_mx_states.zip)
